```{r data set up and reorganization}

se_dat <- read.csv("../data/se.csv")
# read in .csv

se_dat_upd <- read.csv ("../data/molt_dat_cml_wel_11_10_22.csv")
# updated .csv for 2021-2022 CML and WEL data

se_dat$start_end <- factor(se_dat$start_end, levels = c('start', 'end'))
se_dat$outcome <- factor(se_dat$outcome, levels = c('Removed', 'Dead',
                                                    'Molted', 'Intermolt'))
# define levels as factors for later graphing

se_dat_upd$hemo_ri <- as.numeric(se_dat_upd$hemo_ri)

# se_dat_upd$start_end <- factor(se_dat_upd$start_end, 
                          # levels = c('start', 'end'))

se_dat_upd$outcome <- factor(se_dat_upd$outcome, 
                         levels = c('Removed', 'Dead','Molted', 
                                    'Intermolt'))

se_dat_fin <- read.csv("../data/se_updated_fin_v2.csv")

as.numeric(se_dat_fin$outcome =="Molted")

se_dat_fin$hemo_ri <- as.numeric(se_dat_fin$hemo_ri)

se_dat_fin$start_end <- factor(se_dat_fin$start_end, 
                           levels = c('start', 'end'))

se_dat_fin$outcome <- factor(se_dat_fin$outcome, 
                         levels = c('Removed','Molted'))

library(ggplot2)
library(dplyr)
library(car)
# load relevant libraries

rem_molt_df <- read.csv("../data/rem_molt_df.csv")

subset_df <- read.csv("../data/gc_data_subset_gutzler.csv")
```

```{r initial vs final hemo RI in gc conditions}
boxplot(hemo_ri ~ start_end:outcome, data=se_dat,
        main = 'Initial vs. Final Hemolymph Protein of Removed, Dead, and 
        Molted Crabs',
        xlab = 'Condition', ylab = 'Hemolymph Protein',
        col= c('steelblue4', 'steelblue4', 'plum', 'plum', 'springgreen4',
               'springgreen4'))

```

```{r initial vs final hemo RI updated}
boxplot(hemo_ri ~ start_end:outcome, data=se_dat_upd,
        main = 'Initial vs. Final Hemolymph Protein of Removed, Dead, and 
        Molted Crabs',
        xlab = 'Condition', ylab = 'Hemolymph Protein',
        col= c('steelblue4', 'steelblue4', 'plum', 'plum',
               'springgreen4','springgreen4'))
```
```{r initial vs final hemo RI in gc conditions cml update}
boxplot(hemo_ri ~ start_end:outcome, data=se_dat_fin,
        main = 'Initial vs. Final Hemolymph Protein of Removed, Dead, and 
        Molted Crabs',
        xlab = 'Condition', ylab = 'Hemolymph Protein',
        col= c('steelblue4', 'steelblue4', 'plum', 'plum', 'springgreen4',
               'springgreen4'))

```

```{r boxplot Initial Hemo Protein in GC conditions}
plot(hemo_ri ~ outcome, data=se_dat,
        main = 'Initial Hemolymph Protein in Green Crabs',
        subset = start_end == "start",
        xlab = 'Condition', ylab = 'Hemolymph Protein',
        col= c('steelblue4', 'plum', 'springgreen4', 'steelblue1'))

# visualizes data looking at different conditions of gc against intermolt
```

```{r boxplot Initial Hemo Protein in GC conditions updated jan}
plot(hemo_ri ~ outcome, data=se_dat_fin,
        subset = start_end == "start" & condo_id == c("WL", "Lab"),
        xlab = 'Condition', ylab = 'Hemolymph Protein',
        col= c('steelblue4', 'plum', 'springgreen4', 'steelblue1'))

```
```{r Initial Hemo Protein in GC conditions without dead category updated}

out_rmi_fin <- factor(se_dat_fin$outcome, levels = c('Removed', 'Molted'))

# sets parameters to compare removed, molted, and intermolt crabs

boxplot(hemo_ri ~ outcome, data=se_dat_fin,
        subset = start_end == "start" & condo_id == "WL" & 
       outcome == c("Removed", "Molted"),
        xlab = NULL, ylab = 'Hemolymph Refractive Index',
        col= c('steelblue4', 'plum', 'springgreen4'))

boxplot(hemo_ri ~ period, data=se_dat_fin,
        subset = start_end == "start" & condo_id == "WL" & 
       outcome == c("Removed", "Molted", "Intermolt"), 
       ylab = 'Hemolymph Refractive Index',
        col= c('steelblue4', 'plum', 'springgreen4'))

t.test(hemo_ri ~ outcome, data=se_dat_fin,
        subset = start_end == "start" & condo_id == "WL" & 
       outcome == c("Removed", "Molted"))

t.test(hemo_ri ~ period, data=se_dat_fin,
        subset = start_end == "start" & condo_id == "WL" & 
       outcome == c("Removed", "Molted"))

boxplot(hemo_ri ~ period, data=rem_molt_df,
        xlab = NULL, ylab = 'Hemolymph Refractive Index',
        col= c('steelblue4', 'plum'))

t.test(hemo_ri ~ period, data=rem_molt_df)

# n = 

```


```{r sig testing Initial Hemo Protein in GC conditions}

fin_ri_mod <- lm(hemo_ri ~ out_rmi_fin, data=se_dat_fin, 
                     subset = start_end == "start" & 
                     condo_id == c("WL","Lab"))
# builds model to evaluate hemo ri vs. crab outcome

nobs(fin_ri_mod)

plot(fin_ri_mod) # tests assumptions of normality
summary(fin_ri_mod)
anova(fin_ri_mod)
car::Anova(fin_ri_mod, type = 3)

fin_ri_aov <- aov (hemo_ri ~ out_rmi_fin, data=se_dat_fin,
                   subset = start_end == "start" & 
                       condo_id == c("WL","Lab"))
TukeyHSD(fin_ri_aov, conf.level = 0.95) 

```

```{r}
boxplot(hemo_color ~ start_end:outcome, data=se_dat,
        main = 'Initial vs. Final Hemolymph Color of Removed, Dead, and 
        Molted Crabs',
        xlab = 'Condition', ylab = 'Hemolymph Color',
        col= c('steelblue4', 'steelblue4', 'plum', 'plum', 'springgreen4',
               'springgreen4'))

```

```{r initial hemo color of crabs}

plot(hemo_color ~ outcome, data=se_dat, 
    main = 'Initial Hemolymph Color of Removed, Dead, and
    Molted Crabs', subset = start_end == "start",
    xlab = 'Condition', ylab = 'Hemolymph Color',
    col= c('steelblue4', 'plum', 'springgreen4'))

```

```{r glm for hemo color}

# glm with outcome as numeric looking specifically at hemo color
as.factor(se_dat_fin$hemo_col)
as.numeric(se_dat_fin$outcome == "Molted")

col_out_mod <- glm(outcome ~ hemo_col, family = binomial, 
                   data = se_dat_fin)

col_out_mod
plot(col_out_mod)

# glm looking at more variables and interactionsa as a result of outcome
# compared with other factors
# glm with binomial dist. because outcome (molted vs. not molt) is bianry
out_mod <- glm(outcome ~ hemo_col + hemo_ri + sex + condo_id + 
                   hemo_col:hemo_ri, family = binomial, data = se_dat_fin)

out_mod
plot(out_mod)

library(dplyr)
library(MASS)

step(out_mod)
stepAIC(out_mod)

# best aic is hemo_col:hemo_ri
```

```{r}

# logistic model testing multiple factors and obtaining significance
# compared to outcome

log_model = glm(period ~ hemo_ri + cw + sex, 
                subset = outcome == "Molted" & start_end == "start" 
                & condo_id == "WL",
                family = binomial, data = se_dat_fin)

plot(log_model)
summary(log_model)

# logistic model used for graphing
log_mod = glm(period ~ hemo_ri, 
                subset = start_end == "start" & condo_id == "WL", 
                family = binomial, data = se_dat_fin)
summary(log_mod)
```

```{r glm predictions period ri}
# subset of se_dat_fin looking specifically at factors we're interested in
df <- subset(se_dat_fin, start_end == "start" & condo_id == "WL" & period == "TRUE",
             na.rm = TRUE)

# Data frame with hp in ascending order
# use these values to establish parameters for predictions
# generates 500 predictions for plot
Predicted_data <- data.frame(hemo_ri=seq(min(df$hemo_ri, na.rm = TRUE),
                                      max(df$hemo_ri, na.rm = TRUE),
                                      len=500))
 
# Fill predicted values using regression model
Predicted_data$period = predict(log_mod, Predicted_data, type="response")
 
# Plot Predicted data and original data points
# plot in base r showing logistic regression
plot(period ~ hemo_ri, data=df, xlab = "Hemolymph Protein",
     ylab = "Probability of Molting within 2 Weeks")
lines(period ~ hemo_ri, Predicted_data, lwd=2, col="green")

# Plot Predicted data and original data points
ggplot(Predicted_data, aes(x=hemo_ri, y=period)) + geom_point() +
    stat_smooth(method="glm", color="blue", se=FALSE,
                method.args = list(family=binomial)) + 
  labs(x="Hemolymph Refractive Index", y="Probability of Molting")
```

```{r}

as.factor(se_dat_fin$outcome, levels = c('Removed','Dead','Molted',
                                         'Intermolt'))
                     
out_mod_ri = glm(outcome ~ hemo_ri + cw + sex,
              subset = start_end == "start" & condo_id == "WL", 
              family = binomial, data = se_dat_fin)
summary(out_mod_ri)

out_mod_col = glm(outcome ~ hemo_col + cw+ sex,
              subset = start_end == "start" && condo_id == "WL", 
              family = binomial, data = se_dat_fin)
summary(out_mod_col)

plot(out_mod)
summary(out_mod)

out_mod2 = glm(outcome ~ cw,
              subset = start_end == "start" & condo_id == "WL", 
              family = binomial, data = se_dat_fin)
summary(out_mod2)

out_mod3 = glm(outcome ~ hemo_ri,
              subset = start_end == "start", 
              family = binomial, data = se_dat_fin)
summary(out_mod3)

# CW impacts output
# not time constrained
```

```{r}

# subset of se_dat_fin looking specifically at factors we're interested in
df_out <- subset(se_dat_fin, start_end == "start" & sex == "M" & 
                     condo_id == 'WL', na.rm = TRUE)

# Data frame with hp in ascending order
# use these values to establish parameters for predictions
# generates 500 predictions for plot
Pred_data <- data.frame(cw=seq(min(df_out$cw, na.rm = TRUE),
                                      max(df_out$cw, na.rm = TRUE),
                                      len=500))
 
# Fill predicted values using regression model
Pred_data$outcome = predict(out_mod2, Pred_data, type="response")
 
# Plot Predicted data and original data points
# plot in base r showing logistic regression
plot(as.numeric(outcome == "Molted") ~ cw, data=df_out, 
     xlab = "Carapace Width (mm)",
     ylab = "Probability of Molting as an outcome",
     main = "Probability of Molting Based on Carapace Width (Male)",
     sub = "Wells Condo")
lines(outcome ~ cw, Pred_data, lwd=2, col="green")

# Plot Predicted data and original data points
ggplot(Pred_data, aes(x=cw, y=outcome)) + geom_point() +
    stat_smooth(method="glm", color="blue", se=FALSE,
                method.args = list(family=binomial)) +
                    xlab("Carapace width (mm)") + 
                    ylab("Probability of molting as an outcome") +
    ggtitle(
        label = "Probability of Molting Based on Carapace Width (Male)",
        subtitle = "Wells Condo")

```

```{r hemolyphm protein as a predicter for outcome}
df_out <- subset(se_dat_fin, start_end == "start" & 
                     condo_id == "WL", na.rm = TRUE)

# Data frame with hp in ascending order
# use these values to establish parameters for predictions
# generates 500 predictions for plot
Pred_data3 <- data.frame(hemo_ri=seq(min(df_out$hemo_ri, na.rm = TRUE),
                                      max(df_out$hemo_ri, na.rm = TRUE),
                                      len=500))
 
# Fill predicted values using regression model
Pred_data3$outcome = predict(out_mod3, Pred_data3, type="response")
 
# Plot Predicted data and original data points
# plot in base r showing logistic regression
plot(as.numeric(outcome == "Molted") ~ hemo_ri, data=df_out, 
     xlab = "Hemolypmh Protein",
     ylab = "Probability of Molting as an outcome")
lines(outcome ~ hemo_ri, Pred_data3, lwd=2, col="green")

# Plot Predicted data and original data points
ggplot(Pred_data3, aes(x=hemo_ri, y=outcome)) + geom_point() +
    stat_smooth(method="glm", color="blue", se=FALSE,
                method.args = list(family=binomial)) +
                    xlab("Hemolypmh Protein") + 
                    ylab("Probability of molting as an outcome") +
    ggtitle(label = "Probability of Molting Based on Hemolymph RI",
            subtitle = "Wells Condo")

```

```{r}
boxplot(hemo_ri ~ hemo_col, data = se_dat_fin, 
      main = "Initial Green Crab Hemolymph Protein vs. Color",
      sub = 'Wells Condo',
      xlab = "Hemolymph Color (on a scale of 1-5)",
      ylab = "Hemolymph Protein",
      col= c('white', 'antiquewhite3', 'bisque3', 'burlywood4',
             'coral4'),
      subset = condo_id == "WL" & start_end == "start")
```