```{r data read in}

# read in relevant documents for this data
# preliminary data used for calcium etc.
gc_dat <- read.csv("../data/prelim_gc_data.csv")

# updated with full data set 2023-01-06

gc_dat_fin <- read.csv("../data/Condo_Data_Raw_CML_WEL_1_6_23.csv")

gc_dat_fin$hemo_col <- factor(gc_dat_fin$hemo_col,
                           levels = c('1', '2', '3', '4', '5'))

gc_dat_fin$hemo_col <- as.factor(gc_dat_fin$hemo_col)

gc_dat_fin$hemo_ri <- as.numeric(gc_dat_fin$hemo_ri)

# data reclassification to avoid errors later

# libraries for data visualization
library(ggplot2)
library(dplyr)
library(gridExtra)
library(MASS)

```

```{r RI vs. Calcium Plot base r}

plot(Ca ~ RI, data = gc_dat, main = "RI vs. Calcium",
      xlab = "Hemolymph RI (%)", ylab = "Calcium (ppm)")
abline(lm (Ca ~ RI, data = gc_dat), col = 4, lwd = 3, )

# correlation plot to look at RI vs. Calcium
# doesn't appear to be a trend

```

```{r RI vs. Calcium Plot ggplot with confidence int.}

gc_dat %>% 
        # pipes molt data into ggplot
  ggplot(aes(x = RI, y = Ca)) + 
        # populates plot with hemo ri and ca info
    geom_point() + geom_smooth(method=lm) + 
        # specifies type of plot -- linear model with 95 percent confidence
        xlab("Protein Refractive Index") + 
        ylab ("Calcium (ppm)")  +
        # renames x and y labels and title
      xlim(3, 12) + 
        # specifies x axis between 3 and 12 for more clear visualization
      theme(panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(), 
              panel.background = element_blank())

```

```{r ca vs ri significance testing}

ca_ri_mod <- lm(Ca ~ RI, data = gc_dat)
nobs(ca_ri_mod) # tells that there are 127 observations used in this model
summary(ca_ri_mod)
anova(ca_ri_mod) # standard anova
car::Anova(ca_ri_mod, type = 3) # type 3 anova for significance testing

# taken from all during molt cycle, leading to lots of variation
# pointing to trend; small r^2 due to assessing crabs at different times of
# molt cycle
```
```{r}
boxplot(Ca ~ Color, data = gc_dat,
      xlab = "Hemolymph Color",
      ylab = "Calcium (ppm)",
      col= c('white', 'aliceblue', 'bisque', 'darksalmon','coral'))

# appears that calcium increases as hemolymph color darkens

```

```{r Ca vs. color}

boxplot(ca ~ hemo_col, data = gc_dat_fin,
      xlab = "Hemolymph Color",
      ylab = "Calcium (ppm)",
      col= c('white', 'aliceblue', 'bisque', 'darksalmon','coral'), 
      subset = period == "TRUE", outline = FALSE)

# appears that calcium increases as hemolymph color darkens
# n = 25 individual crabs
# n = 11, 10, 36, 6, 2
```

```{r}

boxplot(hemo_ri ~ hemo_col, data = gc_dat_fin,
      xlab = "Hemolymph Color",
      ylab = "Hemolymph Refractive Index",
      col= c('white', 'aliceblue', 'bisque', 'darksalmon','coral'),
      subset = condo_id == "WL" & 
        outcome == c('Molted', 'Removed'))

```


```{r interaction effects of RI and Ca on hemo color}

ri_col_mod = lm(Color ~ RI + Ca + RI:Ca, data = gc_dat)
# model for analyzing the effect of ri and ca on color, as well as the
# interaction between the two

summary(ri_col_mod)
anova(ri_col_mod)
car::Anova(ri_col_mod, type = 3)

car::Anova(lm(Color ~ Ca, data = gc_dat), type = 3)
car::Anova(lm(Color ~ RI, data = gc_dat), type = 3)
# interaction model to assess whether or not hemolymph color is altered by
# the interaction between RI and Ca
```


```{r Tukey HSD test and anova for color and RI fin}

fcol_fin <- factor(gc_dat_fin$hemo_col)
# color is on a scale of 1-5; appears as "numeric"; categorical factor

ri_col_aov_fin <- aov (hemo_ri ~ fcol_fin, data=gc_dat_fin,
                       subset = condo_id == "WL")
summary(ri_col_aov_fin)
# type 1 aov used for Tukey test
# tests between categories: is 1 dif. than 2, etc.

TukeyHSD(ri_col_aov_fin, conf.level = 0.95) 
```

```{r}

wl_col_aov_fin <- aov (hemo_ri ~ hemo_col, data=gc_dat_fin, 
                       subset = condo_id == "WL" & period == "TRUE" 
                       & outcome == c('Molted', 'Removed'))
summary(wl_col_aov_fin)
# type 1 aov used for Tukey test
# tests between categories: is 1 dif. than 2, etc.

TukeyHSD(wl_col_aov_fin, conf.level = 0.95) 

```

```{r Tukey HSD test for color and cai}

fcol <- factor(gc_dat$Color)
# color is on a scale of 1-5; appears as "numeric"; categorical factor

ri_ca_aov <- aov (Ca ~ fcol, data=gc_dat)
summary(ri_ca_aov)

TukeyHSD(ri_ca_aov, conf.level = 0.95) 
# run tukey model
# 2-1, 3-1, 4-1 are significantly different; other categories are the same
```

