```{r .csv and library read in}

molt_dat <- read.csv("../data/wl_molt_dat.csv")
# read in .csv
# contains information from WL 2022
# used for preliminary graphs

molt_dat_2 <- read.csv("../data/wl_cml_molt_dat.csv")
# read in updated .csv
# contains information from 2021, 2022, CML, and WL until 08-2022

molt_dat_upd <- read.csv("../data/molt_dat_cml_wel_11_10_22.csv")
# read in updated .csv
# contains information from 2021, 2022, CML and WL as of 11-2022

molt_dat_upd$hemo_ri <- as.numeric(molt_dat_upd$hemo_ri)

molt_dat_fin <- read.csv("../data/wl_cml_molt_dat_final.csv")

molt_dat_fin$hemo_ri <- as.numeric(molt_dat_fin$hemo_ri)
molt_dat_fin$days_from_molt <- as.numeric(molt_dat_fin$days_from_molt)

library(dplyr)
library(car)
library(ggplot2)
# load relevant libraries for stats analysis
```

```{r ri and days to molt r plot}

# 2022 WL crabs

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     main = "Hemolymph RI as Green Crabs Approach Molt (n=13)",
     xlim = rev(range(days_from_molt)),
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")
abline(lm (hemo_ri ~ days_from_molt, data = molt_dat), col = 4, lwd = 3)

# plots hemo ri vs days from molt for all 13 crabs
# need to reverse x axis to count down to molt
# appears to be downward trend in hemolymph RI as crabs approach molt
# need to investigate on an individual level
```

```{r}
# WL and CML 2021-2022

plot(hemo_ri ~ days_from_molt, data = molt_dat_upd,
     main = "Hemolymph RI as Green Crabs Approach Molt (n=13)",
     xlim = rev(range(days_from_molt)),
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")
abline(lm (hemo_ri ~ days_from_molt, data = molt_dat), col = 4, lwd = 3)

```

```{r}
# most updated

plot(hemo_ri ~ days_from_molt, data = molt_dat_fin,
     main = "Hemolymph RI as Green Crabs Approach Molt",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")
abline(lm (hemo_ri ~ days_from_molt, data = molt_dat), col = 4, lwd = 3)

```

```{r ggplot scatter plot}

# WL 2022 data

molt_dat %>% 
        # pipes molt data into ggplot
  ggplot(aes(x = days_from_molt, y = hemo_ri)) + 
        # populates plot with hemo ri info and defines color with crab ID
    geom_point() + geom_smooth(method=lm) + 
        # specifies type of plot -- linear model with 95 percent confidence
        scale_x_reverse() + 
        # reverses x axis so information counts down to molt
        xlab("Days from molt") + 
        ylab ("Hemolymph RI") +
        ggtitle("Hemolymph protein as green crabs approach molt")
        # renames x and y labels and title

```


```{r}

# WL CML 2021-2022 data
molt_dat_upd %>% 
        # pipes molt data into ggplot
  ggplot(aes(x = days_from_molt, y = hemo_ri)) + 
        # populates plot with hemo ri info and defines color with crab ID
    geom_point() + geom_smooth(method=lm) + 
        # specifies type of plot -- linear model with confidence int
        scale_x_reverse() + 
        # reverses x axis so information counts down to molt
        xlab("Days from molt") + 
        ylab ("Hemolymph RI") +
        ggtitle("Hemolymph RI as green crabs approach molt (39 crabs)")
        # renames x and y labels and title


```

```{r}

# upd data
molt_dat_fin %>% 
        # pipes molt data into ggplot
  ggplot(aes(x = days_from_molt, y = hemo_ri)) + 
        # populates plot with hemo ri info and defines color with crab ID
    geom_point() + geom_smooth(method=lm) + 
        # specifies type of plot -- linear model with confidence int
        scale_x_reverse() + 
        # reverses x axis so information counts down to molt
        xlab("Days from molt") + 
        ylab ("Hemolymph RI") +
        ggtitle("Hemolymph RI as green crabs approach molt (57 crabs)")
        # renames x and y labels and title


```

```{r hemo ri vs days from molt ggplot with gridded background}

# WL 2022 data

library(ggplot2)
library(dplyr)

molt_dat %>% 
        # pipes molt data into ggplot
  ggplot(aes(x = days_from_molt, y = hemo_ri, colour = crab_id)) + 
        # populates plot with hemo ri info and defines color with crab ID
    geom_point() + geom_line() + 
        # specifies type of plot - scatter linear plot with crab IDs
        scale_x_reverse() + 
        # reverses x axis so information counts down to molt
        xlab("Days from molt") + 
        ylab ("Hemolymph RI") +
        ggtitle("Hemolymph RI as green crabs approach molt (n = 13)") +
        # renames x and y labels and title
        labs(col = "Crab ID") 
        # changes legend title
```

```{r hemo ri vs days from molt ggplot with gridded background}

# CML WL 2021 2022 data

library(ggplot2)
library(dplyr)

molt_dat_upd %>% 
        # pipes molt data into ggplot
  ggplot(aes(x = days_from_molt, y = hemo_ri, colour = crab_id)) + 
        # populates plot with hemo ri info and defines color with crab ID
    geom_point() + geom_line() + 
        # specifies type of plot - scatter linear plot with crab IDs
        scale_x_reverse(limits = c(32, 0)) + 
        # reverses x axis so information counts down to molt sets axis
        xlab("Days from molt") + 
        ylab ("Protein Concentration") +
        ggtitle("Hemolymph protein as green crabs approach molt (n = 39)") +
        # renames x and y labels and title
        labs(col = "Crab ID") + 
        # changes legend title
        theme(legend.position = "none") +
        # removes legend
        theme(panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(), 
              panel.background = element_blank())
      
```

```{r hemo ri vs days from molt ggplot without gridded background}

# WL 2022 data

library(ggplot2)
library(dplyr)

molt_dat %>% 
        # pipes molt data into ggplot
  ggplot(aes(x = days_from_molt, y = hemo_ri, colour = crab_id)) + 
        # populates plot with hemo ri info and defines color with crab ID
    geom_point() + geom_line() +
        # specifies type of plot - scatter linear plot with crab ids
        scale_x_reverse() + 
        # reverses x axis so information counts down to molt
        xlab("Days from molt") + 
        ylab ("Protein Concentration") +
        ggtitle("Hemolymph protein as green crabs approach molt") +
        # renames x and y labels and title
        labs(col = "Crab ID") + 
        # changes legend title
        theme(panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(), 
              panel.background = element_blank())
        # removes background grid from plot

```

```{r ri days from molt anova}

# WL 2022 data

ri_mod <- lm(hemo_ri ~ days_from_molt, data = molt_dat)
summary(ri_mod)
anova(ri_mod)
car::Anova(ri_mod, type = 3)

# linear models for significance testing 
# r square of 0.22 -- weak correlation

```

```{r ri days from molt anova}

# WL CML 2022 data

ri_mod_fin <- lm(hemo_ri ~ days_from_molt, data = molt_dat_fin)
summary(ri_mod_fin)
anova(ri_mod_fin)
car::Anova(ri_mod_fin, type = 3)

# linear models for significance testing 
# r square of 0.04 -- no corellation

```

```{r}
# CML WL all data

ri_mod <- lm(hemo_ri ~ days_from_molt, data = molt_dat_2)
summary(ri_mod)
anova(ri_mod)
car::Anova(ri_mod, type = 3)

# linear models for significance testing 
# r square of 0.22 -- weak correlation

```

```{r hemo color and days to molt plot}

# WL 2022 data

plot(hemo_color ~ days_from_molt, data = molt_dat,
     main = "Hemolymph Color as Green Crabs Approach Molt (n=13)",
     xlim = rev(range(days_from_molt)),
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color")
abline(lm (hemo_color ~ days_from_molt, data = molt_dat), col = 4, lwd = 3)


boxplot(days_from_molt ~ hemo_color, data = molt_dat)

# plots hemo color vs days from molt for all 13 crabs
# need to reverse x axis to count down to molt
# doesn't appear to be strong trend or correlation

```
```{r hemo color and days to molt plot}

# WL CML Final 2022 data

plot(hemo_color ~ days_from_molt, data = molt_dat_fin,
     main = "Hemolymph Color as Green Crabs Approach Molt (n=13)",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color")
abline(lm (hemo_color ~ days_from_molt, data = molt_dat), col = 4, lwd = 3)


boxplot(days_from_molt ~ hemo_color, data = molt_dat_fin)

```

```{r hemo color vs days from molt ggplot with gridded background}

# WL 2022 data

library(ggplot2)
library(dplyr)

molt_dat %>% 
        # pipes molt data into ggplot
  ggplot(aes(x = days_from_molt, y = hemo_color, colour = crab_id)) + 
        # populates plot with hemo color info and defines color with crab ID
    geom_point() + geom_line() + 
        # specifies type of plot
        scale_x_reverse() + 
        # reverses x axis so information counts down to molt
        xlab("Days from molt") + 
        ylab ("Hemolymph Color") +
        ggtitle("Hemolymph color as green crabs approach molt (n = 13") +
        # renames x and y labels and title
        labs(col = "Crab ID") + # changes legend title
  theme(panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(), 
              panel.background = element_blank())
        # removes background grid from plot
```

```{r hemo color anova}

# WL 2022 data

col_mod <- lm(hemo_color ~ days_from_molt, data = molt_dat)
summary(col_mod)
anova(col_mod)
car::Anova(col_mod, type = 3)

# linear models for significance testing 

```


```{r individual crab hemo color trends over time}

# WL 2022 data
# individual hemo color graphs over time

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBGB",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBGG",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBGB",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBGY",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBKR",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBWK",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBYB",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGBR",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGBY",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGGW",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGGY",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGKG",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGKR",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")

plot(hemo_color ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGW",
     xlab = "Days From Molt", 
     ylab = "Hemolymph Color",
     type = "b")
```

```{r individual ri graphs over time}

# individual RI graphs over time
# appears that as crabs approach molt, RI decreases

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBGB",
     xlab = "Days From Molt",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBGG",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBGB",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBGY",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBKR",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBWK",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GBYB",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGBR",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGBY",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGGW",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGGY",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGKG",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGKR",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")

plot(hemo_ri ~ days_from_molt, data = molt_dat,
     subset = crab_id == "GGW",
     xlab = "Days From Molt", 
     ylab = "Hemolymph RI",
     type = "b")
```